# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714f56ef96088e2f2a49c1a684da1acb3fe5126d566a7607c4dc8599727f8ecb7ff2749b2f7a8d3329b3e619bf6a4d33966c121f4b3519d50eabc7b528cc289f

test:
  secret_key_base: ad039108398f0a848f82b24f8bba5595e3210375ddef17418339047b862b881573fe9073e50b8b94e9912cd86434e83276e0b67ae50d5cf85c990b517208e431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
